# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

# default for full mobile function was height =500, width=780.
my_leaflet <- function(height = 650, width = 970){
  leaflet::leaflet(height = height, width = width) |>
    leaflet::addTiles() |>
    leaflet::addProviderTiles("Esri.WorldImagery", group = "Ortho") |>
    leaflet::addProviderTiles("Esri.WorldTopoMap", group = "Topo") |>
    leaflet.extras::addFullscreenControl()
}
